module.exports = [
    {
        id: 1,
        first_name: "Timo",
        last_name: "Huennebeck",
        email: "hello@timohuennebeck.com",
        image_url: "https://imgur.com/2iIgpXm",
        role: "student",
    },
    {
        id: 2,
        first_name: "Manuela",
        last_name: "Doe",
        email: "manuela@example.com",
        image_url: "https://i.imgur.com/EY5zHI5.jpg",
        role: "teacher",
    },
    {
        id: 3,
        first_name: "John",
        last_name: "Smith",
        email: "john@example.com",
        image_url: "https://i.imgur.com/uSigcEc.jpg",
        role: "teacher",
    },
    {
        id: 4,
        first_name: "Emilia",
        last_name: "Johnson",
        email: "emilia@example.com",
        image_url: "https://i.imgur.com/xqnWKVs.jpg",
        role: "teacher",
    },
    {
        id: 5,
        first_name: "Melissa",
        last_name: "Williams",
        email: "melissa@example.com",
        image_url: "https://i.imgur.com/XPSFZgM.jpg",
        role: "teacher",
    },
    {
        id: 6,
        first_name: "Luján",
        last_name: "Yaiza",
        email: "luján@example.com",
        image_url: "https://i.imgur.com/9i0RZ0G.jpg",
        role: "teacher",
    },
    {
        id: 7,
        first_name: "Sosimo",
        last_name: "Covadonga",
        email: "sosimo@example.com",
        image_url: "https://i.imgur.com/2cb1VYE.jpg",
        role: "teacher",
    },
    {
        id: 8,
        first_name: "Rosalva",
        last_name: "Candela",
        email: "rosalva@example.com",
        image_url: "https://i.imgur.com/2dzEe91.jpg",
        role: "teacher",
    },
];
